# -*- coding: utf-8 -*-
"""Robotics Lab 6 Manual.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ypy0EnZZjvaqc6tHa8s6K_CUW6x5GdFu
"""

# Phoebe Esser Katz
# April 19, 2025
# Robotics Lab 6: Chess part 1

from interbotix_xs_modules.arm import InterbotixManipulatorXS
import math
import numpy as np

import sys

def main():
    bot = InterbotixManipulatorXS("px100", "arm", "gripper")

  #Dictionaries
    waist = {1: -0.1687, 2: -0.1549, 3: -0.1135, 4: -0.096} # dictionary waist coordinates
    shoulder = {1: -0.074, 2: 0.1871, 3: 0.4786, 4: 1.149} # dictionary shoulder coordinates
    elbow = {1: 0.615, 2: 0.1764, 3: -0.3405, 4: -1.6812} #dictionary elbow coordinates
    wrist = {1: 1.02, 2: 1.181, 3: 1.3929, 4: 1.9236} #dictionary wrist coordinates

  ####READ IN
    if len(sys.argv) > 1:
      pick_location = int(sys.argv[1])
      place_location = int(sys.argv[2])
    else:
      print("Please provide pick and place location numbers between 1 and 4.")

  #translate pick and place locations into coordinates
    waistI = waist[pick_location]
    shoulderI = shoulder[pick_location]
    elbowI = elbow[pick_location]
    wristI = wrist[pick_location]

    waistF = waist[place_location]
    shoulderF = shoulder[place_location]
    elbowF = elbow[place_location]
    wristF = wrist[place_location]

  #Move Robot to Home
    bot.arm.set_single_joint_position("wrist_angle", 0)
    bot.arm.set_single_joint_position("elbow", 0)
    bot.arm.set_single_joint_position("shoulder", 0)

  #Move Robot to pick up location / pick up
    bot.gripper.open()
    bot.arm.set_single_joint_position("waist", waistI)
    bot.arm.set_single_joint_position("shoulder", shoulderI)
    bot.arm.set_single_joint_position("wrist_angle", wristI)
    bot.arm.set_single_joint_position("elbow", elbowI)
    bot.gripper.close()

  #Move Robot Back to Home
    bot.arm.set_single_joint_position("waist", 0)
    bot.arm.set_single_joint_position("elbow", 0)
    bot.arm.set_single_joint_position("shoulder", 0)
    bot.arm.set_single_joint_position("wrist_angle", 0)

  #Move Robot to pick up location / pick up
    bot.arm.set_single_joint_position("waist", waistF)
    bot.arm.set_single_joint_position("shoulder", shoulderF)
    bot.arm.set_single_joint_position("wrist_angle", wristF)
    bot.arm.set_single_joint_position("elbow", elbowF)
    bot.gripper.open()

  #Move Robot Back to Home
    bot.arm.set_single_joint_position("waist", 0)
    bot.arm.set_single_joint_position("elbow", 0)
    bot.arm.set_single_joint_position("shoulder", 0)
    bot.arm.set_single_joint_position("wrist_angle", 0)

  #Move Robot to Sleep Position
    bot.arm.go_to_sleep_pose()

if __name__=='__main__':
    main()

